language: cpp
os: linux
sudo: required
dist: trusty
compiler: gcc

install:
  - travis_wait 30 ./setup/travis_install.sh lsst-sims nose pandas pylint
  - ln -sf /home/travis/miniconda/lib/libssl.so.1.0.0 /home/travis/miniconda/lib/libssl.so.10
  - ln -sf /home/travis/miniconda/lib/libcrypto.so.1.0.0 /home/travis/miniconda/lib/libcrypto.so.10
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source eups-setups.sh
  - conda install --yes astropy=1.1.2
  - pip install coveralls
  - git clone https://github.com/DarkEnergyScienceCollaboration/imSim.git ../imSim
  - setup lsst_sims
  - eups declare -r ../imSim imsim -t current
  - eups declare -r . imsimdeep -t current
  - setup imsimdeep
  - scons opt=3

cache:
  directories:
  - $HOME/miniconda.tarball
  timeout: 600

script:
  - nosetests --with-coverage --cover-package=desc.imsimdeep
  - pylint -r n --py3k `find . -name \*.py -print | grep -v instcat_utils.py`

after_success:
  - pylint -r n --rcfile=.pylintrc `find . -name \*.py -print | grep -v instcat_utils.py`
  - coveralls
